### ISSUE TITLE
Error occurred during parsing: Unexpected EOF inside bytes field.

### ISSUE THREAD

**Issue by jhlater** [xingwenge/canal-php#1]
canal装在本机，端口也是默认，我执行了sample下的 index.php,提示如标题，请问这是什么原因引起？

**Comment by xingwenge** [comment]
单次拉消息太多导致。

**Comment by zgxv** [comment]
修改为$conn->get(1);还是报同样的错，需要怎么修改啊

**Comment by xingwenge** [comment]
@zgxv 我这是没问题的。能提供mysql数据源和具体变更操作么。

**Comment by zgxv** [comment]
> 单次拉消息太多导致。



> @zgxv 我这是没问题的。能提供mysql数据源和具体变更操作么。

canal连接的是已经存在的数据库，postion位置是新的，php运行时就报错，还没有变更操作

**Comment by xingwenge** [comment]
@zgxv 加我QQ470703808

> > 单次拉消息太多导致。
> 
> > @zgxv 我这是没问题的。能提供mysql数据源和具体变更操作么。
> 
> canal连接的是已经存在的数据库，postion位置是新的，php运行时就报错，还没有变更操作

@zgxv 加我QQ470703808
