### ISSUE TITLE
php客户端消费速率问题

### ISSUE THREAD

**Issue by nickhuang1127** [xingwenge/canal-php#11]
我搭建的单机canal和单个php客户端来进行消费，中间涉及重组数据再输出到es,所以消费效率不高，35条/s，消费方式是tcp，同步ack。请问在tcp模式下有什么好的办法提高消费效率吗？php客户端如何设置异步ack呢，有例子吗？

**Comment by xingwenge** [comment]
可以启多个进程消费，需要考虑消息顺序性

**Comment by nickhuang1127** [comment]
> 可以启多个进程消费，需要考虑消息顺序性

大神好，我试着开启多个进程

**Comment by nickhuang1127** [comment]
> 可以启多个进程消费，需要考虑消息顺序性

好的，谢谢

**Comment by feng99** [comment]
> > 可以启多个进程消费，需要考虑消息顺序性
> 
> 好的，谢谢

消息顺序性该如何处理?
