### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by nickhuang1127** [xingwenge/canal-php#14]
canal启动后，canal.log会一直报“something goes wrong with channel:[id: 0x7cb4dc0d, /xx.xx.x.xxx:41776 => /xx.xx.x.xxx:11111], exception=java.io.IOException: Connection reset by peer”，出现频率每分钟基本都有，但是canal可以正常监听到binlog数据。

搭建方式：单例Simple(docker容器)
客户端：php客户端(官方demo)

**Comment by xingwenge** [comment]
可以尝试下把获取包size设置小些

**Comment by nickhuang1127** [comment]
@xingwenge  把获取的包从100改为10 ，还是不行，另外如果不启动PHP客户端，只开启canal-server，canal.log也是一直报这个错，是否跟canalserver监听mysql-binlog有关系呢？

**Comment by nickhuang1127** [comment]
已解决，是k8s的健康监测引起的。
