### ISSUE TITLE
拉取消息提示packet type=CLIENTAUTHENTICATION is NOT supported!

### ISSUE THREAD

**Issue by THE-BASIC-LAW** [xingwenge/canal-php#19]
Exception 'Exception' with message 'get data error. error code:400, error message:packet type=CLIENTAUTHENTICATION is NOT supported!'

in /mnt/c/futu/ns_oss/vendor/xingwenge/canal_php/src/adapter/CanalConnectorBase.php:205

Stack trace:
#0 /mnt/c/futu/ns_oss/vendor/xingwenge/canal_php/src/adapter/CanalConnectorBase.php(151): xingwenge\canal_php\adapter\CanalConnectorBase->getWithoutAck()
#1 /mnt/c/futu/ns_oss/console/controllers/CanalController.php(107): xingwenge\canal_php\adapter\CanalConnectorBase->get()

**Comment by THE-BASIC-LAW** [comment]
同样的代码，直接拉取示例代码用cli运行是可以的，放到Yii框架下运行会报这个错，原因是什么呢

**Comment by xingwenge** [comment]
拉取消息是长连接，web是短连接，建议不使用

**Comment by THE-BASIC-LAW** [comment]
> 拉取消息是长连接，web是短连接，建议不使用

不是web，是控制台脚本，只不过是在框架下运行

**Comment by liasica** [comment]
> 本，只不过是在框架下运行

你最后如何解决的？
