### ISSUE TITLE
客户端设置filter，过滤某些表，无效

### ISSUE THREAD

**Issue by dingshiwei** [xingwenge/canal-php#3]
看其他语言现在是支持的，现在是还没有添加吗？可否给个联系方式？

**Comment by xingwenge** [comment]
@dingshiwei 没测试filter，qq:470703808

**Comment by xingwenge** [comment]
> 看其他语言现在是支持的，现在是还没有添加吗？可否给个联系方式？

没测试filter。qq:470703808

**Comment by xingwenge** [comment]
已测，过滤没有问题
