### ISSUE TITLE
只能用命令行运行么？我部署在Nginx下，会报错502错误。

### ISSUE THREAD

**Issue by ChenRuihua** [xingwenge/canal-php#6]
如题，可以部署在nginx下么？

**Comment by xingwenge** [comment]
php-canal 是tcp长连接，nginx web是tcp短连接，浏览器用户超过了连接时间，会关闭浏览器客户端连接，所以502了。
如果要在nginx里，需把tcp连接超时时间取消，用flush()刷新输出浏览器页面，应该就可以放到nginx里了

**Comment by feng99** [comment]
php cli模式启动更合理  放到nginx里不合理
